# Workflow para construir e publicar um site Jekyll no GitHub Pages
name: Deploy Jekyll site to Pages

on:
  # Executa em pushes para o branch padrão
  push:
    branches: ["main"]
  # Permite que você execute este workflow manualmente na aba Actions
  workflow_dispatch:

# Define as permissões do GITHUB_TOKEN para permitir o deploy no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy concorrente
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # A versão do Ruby que o Pages usa
          bundler-cache: true # Armazena em cache as dependências
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        # Usa o script de build do GitHub Pages para garantir compatibilidade
        run: bundle exec jekyll build --source . --destination _site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  # Job de deploy
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
